### ISSUE TITLE
Module ssdp missing

### ISSUE THREAD

**Issue by RobvanderDoes** [OpenViX/HRTunerProxy#24]
After installing the plugin I get:
```
< 10366.380> [PluginComponent] Plugin  Extensions/WebInterface failed to load: No module named plugin
< 10366.482> [PluginComponent] Plugin  SystemPlugins/HRTunerProxy failed to load: No module named ssdp
< 10366.483> Traceback (most recent call last):
< 10366.484>   File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 53, in readPluginList
< 10366.484>   File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
< 10366.484>   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/HRTunerProxy/plugin.py", line 26, in <module>
< 10366.485> ImportError: No module named ssdp
< 10366.758> [TMDb] fallback to default Enigma2 Translation for TMDb
< 10366.761> [TMDb] fallback to default Enigma2 Translation for TMDb Infos ...
< 10366.765> [TMDb] fallback to default Enigma2 Translation for TMDb
< 10366.768> [TMDb] fallback to default Enigma2 Translation for TMDb Infos ...
< 10366.924> [PluginComponent] Plugin  Extensions/WebInterface failed to load: No module named plugin
< 10367.008> [PluginComponent] Plugin  SystemPlugins/HRTunerProxy failed to load: No module named ssdp
< 10367.009> Traceback (most recent call last):
< 10367.009>   File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 53, in readPluginList
< 10367.010>   File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
< 10367.010>   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/HRTunerProxy/plugin.py", line 26, in <module>
< 10367.010> ImportError: No module named ssdp
< 
```
A couple of days ago all was fine.

**Comment by andyblac** [comment]
thanks, https://github.com/OpenViX/HRTunerProxy/commit/2f6b2fedad488b936d417f060d6ed726777e9cd9 should fix for next build.

**Comment by RobvanderDoes** [comment]
Thanks, indeed fixed,
