### ISSUE TITLE
Crasch after open Plugin

### ISSUE THREAD

**Issue by sickboy2711** [OpenViX/HRTunerProxy#43]
Hello I have installed teh Plugin on mx Newnigma Box (DM920)
after i Start the Plugin to set up i get a crashlog (newnigma greenscreen)

**Comment by yannicsack** [comment]
I've the same issue:

Dreambox 920 (Newenigma) crashes with greenscreen after trying to setup the plugin

plugin.py line 364: 
**session.open(HRTunerProxy_Setup)**

**Comment by Huevos** [comment]
Crash log?

**Comment by yannicsack** [comment]
swig director exception (SWIG director method error.)
0xb40f9068(sp=0xbef55958) <__cxa_throw+168>
0x3d668c(sp=0xbef55970) <SwigDirector_eActionSlot::action_func2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+848>
0xdb900(sp=0xbef559b8) <eActionMap::unbindKeyDomain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+1164>
0xda0ac(sp=0xbef55a08) <eActionMap::keyPressed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)+1480>
0x373750(sp=0xbef55a90) <our_terminate()+597008>
0xb4b747ec(sp=0xbef55ad0) <PyEval_EvalFrameEx+24760>
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/enigma.py", line 8610, in __call__
    return ret(*args, **kwargs)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 87, in action
    return ActionMap.action(self, contexts, action)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 70, in action
    res = act()
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 110, in okbuttonClick
    selection[1]()
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 65, in __call__
    self.fnc(*self.args)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/HRTunerProxy/plugin.py", line 394, in HRTunerProxy_SetupMain
    session.open(HRTunerProxy_Setup)
  File "/usr/lib/enigma2/python/mytest.py", line 483, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 384, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/mytest.py", line 419, in doInstantiateDialog
    readSkin(dlg, None, dlg.skinName, desktop)
  File "/usr/lib/enigma2/python/skin.py", line 890, in readSkin
    parseWidgets(name, myscreen, screen, skin_path_prefix, visited_components)
  File "/usr/lib/enigma2/python/skin.py", line 912, in parseWidgets
    parseWidget(name, widget, screen, skin_path_prefix, visited_components, group)
  File "/usr/lib/enigma2/python/skin.py", line 977, in parseWidget
    raise SkinError("component with name '" + wname + "' was not found in skin of screen '" + name + "'!")
skin.SkinError: {Nuke.Evo/skin.xml}: component with name 'hinttext' was not found in skin of screen 'HRTunerProxy_Setup'!
]]>

**Comment by yannicsack** [comment]
First issue can be resolved by changing skin to default. However, the plugin crashes again in the next step (changing tuner type). 

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/enigma.py", line 8610, in __call__
    return ret(*args, **kwargs)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 87, in action
    return ActionMap.action(self, contexts, action)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 70, in action
    res = act()
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 258, in keyRight
    self["config"].handleKey(KEY_RIGHT)
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 50, in handleKey
    selection[1].handleKey(key)
  File "/usr/lib/enigma2/python/Components/config.py", line 380, in handleKey
    i = self.choices.index(self.value)
  File "/usr/lib/enigma2/python/Components/config.py", line 250, in index
    return self.__list__().index(value)
-------
ValueError: 'multi' is not in list
