### ISSUE TITLE
skin is missing attributes

### ISSUE THREAD

**Issue by Serph91P** [OpenViX/HRTunerProxy#48]
hey I hope someone can help.

This is the crashlog I get. plugin just crashing after install.

`WARNING!!!!: unsupported skin attribute alternate_row_color=zebra
warning, skin is missing element pixmap in <class 'Screens.Menu.MainMenu'>
allocating new converter!
create buffer for widget 600 x 1080
action ->  OkCancelActions ok
okbuttonClick
allocating new converter!
WARNING!!!!: unsupported skin attribute alternate_row_color=zebra
WARNING!!!!: unsupported skin attribute itemheight=200
WARNING!!!!: unsupported skin attribute itemwidth=200
allocating new converter! (2 times)
create buffer for widget 600 x 1080
unknown action WizardActions/down! typo in keymap?
unknown action WizardActions/down! typo in keymap?
unknown action WizardActions/down! typo in keymap?
unknown action WizardActions/down! typo in keymap?
unknown action WizardActions/down! typo in keymap?
unknown action WizardActions/down! typo in keymap?
unknown action WizardActions/down! typo in keymap?
unknown action WizardActions/down! typo in keymap?
unknown action WizardActions/down! typo in keymap?
action ->  WizardActions ok
reused converter!
warning, skin is missing element key_yellow in <class 'Plugins.SystemPlugins.HRTunerProxy.plugin.HRTunerProxy_Setup'>
warning, skin is missing element key_blue in <class 'Plugins.SystemPlugins.HRTunerProxy.plugin.HRTunerProxy_Setup'>
warning, skin is missing element button_red in <class 'Plugins.SystemPlugins.HRTunerProxy.plugin.HRTunerProxy_Setup'>
warning, skin is missing element button_green in <class 'Plugins.SystemPlugins.HRTunerProxy.plugin.HRTunerProxy_Setup'>
warning, skin is missing element button_blue in <class 'Plugins.SystemPlugins.HRTunerProxy.plugin.HRTunerProxy_Setup'>
warning, skin is missing element button_yellow in <class 'Plugins.SystemPlugins.HRTunerProxy.plugin.HRTunerProxy_Setup'>
warning, skin is missing element key_green in <class 'Plugins.SystemPlugins.HRTunerProxy.plugin.HRTunerProxy_Setup'>
warning, skin is missing element key_red in <class 'Plugins.SystemPlugins.HRTunerProxy.plugin.HRTunerProxy_Setup'>
swig director exception (SWIG director method error.)
0xb40e6068(sp=0xbeea65b0) <__cxa_throw+168>
0x3d668c(sp=0xbeea65c8) <SwigDirector_eActionSlot::action_func2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+848>
0xdb900(sp=0xbeea6610) <eActionMap::unbindKeyDomain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+1164>
0xda0ac(sp=0xbeea6660) <eActionMap::keyPressed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)+1480>
0xd0bc8(sp=0xbeea66e8) <keyEvent(eRCKey const&)+276>
0x2a4c04(sp=0xbeea6718) <eRCInput::keyPressed(eRCKey const&)+252>
0x2a65fc(sp=0xbeea6740) <eRCDeviceInputDev::handleCode(long)+160>
0x2a3a50(sp=0xbeea6760) <eRCInputEventDriver::keyPressed(int)+120>
0xe0948(sp=0xbeea6788) <eSocketNotifier::activate(int)+272>
0xe2ab4(sp=0xbeea67c8) <eMainloop_native::processOneEvent(int)+2760>
0x2db6b8(sp=0xbeea7a00) <eMainloopQt::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+156>
0xb522f22c(sp=0xbeea7b28) <QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)+276>
0xb5238498(sp=0xbeea7b70) <QCoreApplication::exec()+148>
0x2db5f8(sp=0xbeea7ba0) <eMainloopQt::runLoop()+24>
0x2e2be4(sp=0xbeea7ba8) <our_terminate()+4260>
0xb4b6150c(sp=0xbeea7bc0) <PyEval_EvalFrameEx+24024>
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/enigma.py", line 8610, in __call__
    return ret(*args, **kwargs)
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 70, in action
    res = act()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 48, in save
    self.run()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 52, in run
    plugin(session=self.session)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/HRTunerProxy/plugin.py", line 450, in HRTunerProxy_SetupMain
    session.open(HRTunerProxy_Setup)
  File "/usr/lib/enigma2/python/mytest.py", line 483, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 384, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/mytest.py", line 426, in doInstantiateDialog
    dlg.applySkin()
  File "/usr/lib/enigma2/python/Components/GUISkin.py", line 116, in applySkin
    self.createGUIScreen(self.instance, self.desktop)
  File "/usr/lib/enigma2/python/Components/GUISkin.py", line 35, in createGUIScreen
    if val.applySkin(desktop, self):
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 34, in applySkin
    return GUIComponent.applySkin(self, desktop, parent)
  File "/usr/lib/enigma2/python/Components/GUIComponent.py", line 39, in applySkin
    skin.applyAllAttributes(self.instance, desktop, self.skinAttributes, parent.scale)
  File "/usr/lib/enigma2/python/skin.py", line 439, in applyAllAttributes
    applySingleAttribute(guiObject, desktop, attrib, value, scale)
  File "/usr/lib/enigma2/python/skin.py", line 238, in applySingleAttribute
    guiObject.setFont(parseFont(value, scale))
-------
AttributeError: 'eListbox' object has no attribute 'setFont'
]]>
		</enigma2crashlog>`

**Comment by Serph91P** [comment]
Ok fixed it, for everyone having the same problem. Load the default skin then it will work!
